name: Chunkview
version: '${project.version}'
main: ${main.class}
api-version: 1.13
author: Cobrex

commands:
  chunkview:
    description: View the boarders of the chunk you are standing in.
    aliases:
      - cv
      - chunkv
    permission: chunkview.view
    permission-message: "You do not have permission to use this command!"
    default: true
    usage: |-
      /chunkview - to view the chunk boarder.
permissions:
  chunkview.view:
    description: Allows use of /chunkview
    default: true
